---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: bff-service
spec: 
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/bff-service
    repoURL: git@github.com:zeabix-cloud-native/ptg-gitops.git
    targetRevision: main
    helm: 
      releaseName: bff-service
  syncPolicy:
    automated: 
      selfHeal: true
    retry: 
      backoff: 
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
