apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-portal.fullname" . }}
  labels:
    {{- include "admin-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port }}
  selector:
    {{- include "admin-portal.selectorLabels" . | nindent 4 }}
