{{- if .Values.appEnv.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "transaction-processor.fullname" . }}-env
  labels:
     {{- include "transaction-processor.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.appEnv.configMap }}
  {{- if (ne $key "enabled") }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}